---

- name: ensure package repository is installed
  template: >
    src=templates/rsyslog.list.j2
    dest=/etc/apt/sources.list.d/rsyslog.list
    owner=root
    group=root
    mode=0644

- name: install rsyslog package
  apt: >
    name=rsyslog
    state=installed
