---

- name: configure local logging
  template: >
    src=templates/local.conf.j2
    dest=/etc/rsyslog.d/local.conf
    owner=root
    group=root
    mode=0600
    backup=yes

  notify: ["restart rsyslog"]
