---

- name: ensure snmp includes file exists
  file: >
    path={{ snmp_includes_dir }}
    owner=root
    group=root
    mode=0755
    state=directory

- name: ensure rsyslog process is monitored by snmpd
  template: >
    src=templates/rsyslog.snmpd.conf.j2
    dest={{ snmp_includes_dir }}/rsyslog.conf
    owner=root
    group=root
    mode=0600
  notify:
    - reload snmpd
