FROM centos:7

# install systemd -- see https://hub.docker.com/_/centos/
RUN yum install -y epel-release && \
  yum swap -y -- remove fakesystemd -- install systemd systemd-libs && \
  (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
  rm -f /lib/systemd/system/multi-user.target.wants/*; \
  rm -f /etc/systemd/system/*.wants/*; \
  rm -f /lib/systemd/system/local-fs.target.wants/*; \
  rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
  rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
  rm -f /lib/systemd/system/basic.target.wants/*; \
  rm -f /lib/systemd/system/anaconda.target.wants/*;

# install dependencies
RUN yum update -y && \
  yum -y install \
    python-pip \
    gcc \
    git \
    libffi-devel \
    openssl-devel \
    python-devel \
    python-setuptools \
    sudo && \
  yum clean all

# install ansible
RUN pip install ansible

# disable requiretty
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

# install ansible inventory file
RUN mkdir - p /etc/ansible && echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

VOLUME ["/sys/fs/cgroup"]
CMD ["/usr/sbin/init"]
